# Generated by Django 5.2.11 on 2026-03-02 07:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='language',
            field=models.CharField(default='en', max_length=50),
        ),
        migrations.AddField(
            model_name='candidate',
            name='parsed_experience',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='parsed_projects',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='parsed_skills',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='min_match_score',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='job',
            name='test_threshold',
            field=models.IntegerField(default=70),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='resume',
            field=models.FileField(default='', upload_to='resumes/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='required_skills',
            field=models.TextField(help_text='Comma separated skills'),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField(default=0.0)),
                ('test_score', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('PARSED', 'Parsed'), ('MATCHING', 'Matching'), ('TESTING', 'Testing'), ('PASSED', 'Passed'), ('FAILED', 'Failed'), ('REJECTED', 'Rejected')], default='PARSED', max_length=20)),
                ('test_start_time', models.DateTimeField(blank=True, null=True)),
                ('test_end_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.job')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('options_json', models.TextField()),
                ('correct_answer', models.CharField(max_length=1)),
                ('candidate_answer', models.CharField(blank=True, max_length=1, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.application')),
            ],
        ),
        migrations.DeleteModel(
            name='TestResult',
        ),
    ]
