# Generated by Django 5.2.11 on 2026-03-02 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_candidate_created_at_candidate_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='match_reasoning',
            field=models.TextField(blank=True),
        ),
    ]
