# Generated by Django 5.2.11 on 2026-03-02 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_candidate_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='candidate_answer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='options_json',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
